### ISSUE TITLE
Python 3 tostring() deprecation warning

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1320]
The "DeprecationWarning: tostring() is deprecated. Use tobytes() instead." warning is seen when running the image and midi tests with the -Wd Python warning option. This is due to the `array.tostring()` method being deprecated in Python 3.

```
>py -3 -Wd -m pygame.tests.image_test -v
pygame 2.0.0.dev3 (SDL 2.0.10, python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
testLoadIcon (__main__.ImageModuleTest)
see if we can load the pygame icon. ... ok
testLoadJPG (__main__.ImageModuleTest)
see if we can load a jpg. ... ok
testLoadPNG (__main__.ImageModuleTest)
see if we can load a png with color values in the proper channels. ... C:\Program Files\Python37\Lib\site-packages\pygame-2.0.0.dev3-py3.7-win-amd64.egg\pygame\tests\test_utils\png.py:783: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  compressed = compressor.compress(tostring(data))
ok
testSaveJPG (__main__.ImageModuleTest)
JPG equivalent to issue #211 - color channel swapping ... ok
testSavePNG24 (__main__.ImageModuleTest)
see if we can save a png with color values in the proper channels. ... ok
testSavePNG32 (__main__.ImageModuleTest)
see if we can save a png with color values in the proper channels. ... ok
test_fromstring__and_tostring (__main__.ImageModuleTest)
Ensure methods tostring() and fromstring() are symmetric. ... C:\Program Files\Python37\Lib\site-packages\pygame-2.0.0.dev3-py3.7-win-amd64.egg\pygame\tests\image_test.py:419: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  rgba_buf = RotateARGBtoRGBA(RotateRGBAtoARGB(rgba_buf))
C:\Program Files\Python37\Lib\site-packages\pygame-2.0.0.dev3-py3.7-win-amd64.egg\pygame\tests\image_test.py:427: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  argb_buf = RotateRGBAtoARGB(rgba_buf)
C:\Program Files\Python37\Lib\site-packages\pygame-2.0.0.dev3-py3.7-win-amd64.egg\pygame\tests\image_test.py:435: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  rgba_buf = RotateARGBtoRGBA(argb_buf)
ok
test_load_bmp_threads (__main__.ImageModuleTest) ... ok
test_load_gif_threads (__main__.ImageModuleTest) ... ok
test_load_jpg_threads (__main__.ImageModuleTest) ... ok
test_load_png_threads (__main__.ImageModuleTest) ... ok
test_load_unicode_path (__main__.ImageModuleTest) ... ok
test_save (__main__.ImageModuleTest) ... ok
test_save_colorkey (__main__.ImageModuleTest)
make sure the color key is not changed when saving. ... ok
test_save_unicode_path (__main__.ImageModuleTest)
save unicode object with non-ASCII chars ... ok
test_to_string__premultiplied (__main__.ImageModuleTest)
test to make sure we can export a surface to a premultiplied alpha string ... ok

----------------------------------------------------------------------
Ran 16 tests in 1.057s

OK
```

```
>py -3 -Wd -m pygame.tests.midi_test -v
pygame 2.0.0.dev3 (SDL 2.0.10, python 3.7.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
test_Input (__main__.MidiInputTest) ... ok
test_close (__main__.MidiInputTest) ... skipped 'No midi Input device'
test_poll (__main__.MidiInputTest) ... skipped 'No midi Input device'
test_read (__main__.MidiInputTest) ... skipped 'No midi Input device'
test_MidiException (__main__.MidiModuleNonInteractiveTest)
Ensures the MidiException is raised as expected. ... ok
test_conversions (__main__.MidiModuleNonInteractiveTest)
of frequencies to midi note numbers and ansi note names. ... ok
test_midiin (__main__.MidiModuleNonInteractiveTest)
Ensures the MIDIIN event id exists in the midi module. ... ok
test_midiout (__main__.MidiModuleNonInteractiveTest)
Ensures the MIDIOUT event id exists in the midi module. ... ok
test_midis2events (__main__.MidiModuleNonInteractiveTest)
Ensures midi events are properly converted to pygame events. ... ok
test_midis2events__extra_event_data (__main__.MidiModuleNonInteractiveTest)
Ensures midi events with extra values are handled properly. ... ok
test_midis2events__extra_event_data_missing_timestamp (__main__.MidiModuleNonInteractiveTest)
Ensures midi events with extra data and no timestamps are handled ... ok
test_midis2events__missing_event_data (__main__.MidiModuleNonInteractiveTest)
Ensures midi events with missing values are handled properly. ... ok
test_get_count (__main__.MidiModuleTest) ... ok
test_get_default_input_id (__main__.MidiModuleTest) ... ok
test_get_default_output_id (__main__.MidiModuleTest) ... ok
test_get_device_info (__main__.MidiModuleTest) ... ok
test_get_init (__main__.MidiModuleTest) ... ok
test_init (__main__.MidiModuleTest) ... ok
test_quit (__main__.MidiModuleTest) ... ok
test_time (__main__.MidiModuleTest) ... ok
test_Output (__main__.MidiOutputTest) ... ok
test_abort (__main__.MidiOutputTest) ... ok
test_close (__main__.MidiOutputTest) ... ok
test_note_off (__main__.MidiOutputTest) ... ok
test_note_on (__main__.MidiOutputTest) ... ok
test_pitch_bend (__main__.MidiOutputTest) ... ok
test_set_instrument (__main__.MidiOutputTest) ... ok
test_write (__main__.MidiOutputTest) ... ok
test_write_short (__main__.MidiOutputTest) ... ok
test_write_sys_ex (__main__.MidiOutputTest) ... C:\Program Files\Python37\Lib\site-packages\pygame-2.0.0.dev3-py3.7-win-amd64.egg\pygame\tests\midi_test.py:204: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  [0xF0, 0x7D, 0x10, 0x11, 0x12, 0x13, 0xF7])
ok

----------------------------------------------------------------------
Ran 30 tests in 3.810s

OK (skipped=3)
```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.4 (64bit) and 2.7.10 (64bit)
- pygame: 2.0.0.dev3 (SDL: 2.0.10) at 3dc30228458e024b1df03ea869899b785a8f4fb1

**Comment by robertpfeiffer** [comment]
Should we fix this by mirroring the nomenclature on Python 3, and adding tobytes/frombytes functions?

**Comment by nthykier** [comment]
@charlesej @robertpfeiffer: Hi, has this been fixed by https://github.com/pygame/pygame/commit/90b4e1127e102ce959a409ace3503451e52955de ? The pull request looks related but did not close this issue.

**Comment by charlesej** [comment]
@nthykier PR #1627 fixes some occurrences of the `tostring` deprecation warning, but others still exist when running the following tests.

`py -3 -Wd -m pygame.tests.image_test -v`
`py -3 -Wd -m pygame.tests.midi_test -v`

**Comment by nthykier** [comment]
Thanks for confirming. :)  I had hoped this was just a case of "missing a Closes".

**Comment by nthykier** [comment]
The image_test should be fixed by #1651 (once merged).  But I am unsure how to approach the `midi_test` (or more correctly the underlying `pypm`).  I can see where the problem is triggered in `pypm.pyx' / `pypm.c`; do we have some documentation describing how to invoke `cython` to get the right result?

**Comment by nthykier** [comment]
I think I figured out (with the cython argument to setup.py)

**Comment by nthykier** [comment]
I think this is fixed now after #1651 and #1656 have been merged. :)
