### ISSUE TITLE
PyGame window stops updating after moving the window to another screen (mac)

### ISSUE THREAD

**Issue by levsa** [pygame/pygame#1720]
If I move the PyGame window from the screen it was started on to another screen, it stops updating itself. It doesn't start updating again even if moved back to the original screen. Nothing in the terminal and Esc quits the application as normally. Tried own application and `python3 -m pygame.examples.aliens`

On macOS Mojave 10.14.6 (18G4032). Graphics Radeon Pro 450 2 GB, Intel HD Graphics 530 1536 MB

**Comment by illume** [comment]
Hi, thanks for the report.

I think this is fixed in pygame 2. Are you using 1.9.6?
You can use the pre-release like so: `python3 -m pip install pygame==2.0.0.dev8`

**Comment by levsa** [comment]
No, I was using `2.0.0.dev6`.

Tested `2.0.0.dev8` now, the issue is still present

**Comment by illume** [comment]
I can't reproduce this on my Mac 10.13.6 with python 3.7.

Can you please try with these two examples to see if they work?

```bash
python3 -m pygame.examples.aliens
```

This one prints out a few diagnostic issues, and renders in a different way to the first.

```bash
python3 -m pygame.examples.setmodescale

renderer: metal flags: 0b1010
accelerated
render to texture
```

**Comment by levsa** [comment]
`pygame.examples.setmodescale` works.
`pygame.examples.aliens` doesn't work :)

Output from `pygame.examples.setmodescale`
```
 lava@3.7.2 ~/src/lava/python/lavalamp/[master] > python3 -m pygame.examples.setmodescale
pygame 2.0.0.dev8 (SDL 2.0.12, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
desktops [(2560, 1440), (1920, 1200)]
renderer: opengl flags: 0b1010
accelerated
render to texture
```

**Comment by MyreMylar** [comment]
I assume this is related to this:

https://github.com/pygame/pygame/issues/1725

**Comment by galexandreg** [comment]
> I assume this is related to this:
> 
> #1725

I don't think so. The aliens example dosen't use SCALED to get a SDL renderer, so I don't see how it could be related.



> I can't reproduce this on my Mac 10.13.6 Intel Iris Pro 1536 MB, NVIDIA GeForce GT 750M with python 3.7. Maybe it's the MacOS version or ATI driver triggering the issue.
> 

I tried it on MacOS 10.15.4, pygame2.0.0.dev8 and Python 3.8.2 and I also can't reproduce it.

**Comment by levsa** [comment]
I've just tested the setup from `setmodescale` in `aliens`.

If I use 

```python
    winstyle = pg.SCALED #0  # |FULLSCREEN
    bestdepth = pg.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pg.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```

it works, and `pg.display.get_renderer_info()` returns: `('opengl', 10)`

But if I use
```python
    winstyle = 0  # |FULLSCREEN
    bestdepth = pg.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pg.display.set_mode(SCREENRECT.size, winstyle, bestdepth)
```
it stops working and `pg.display.get_renderer_info()` returns `None`

**Comment by shortbow123** [comment]
This also happens to me, all I wanted to do was to enter some code into idle but it decided to not work, I went to flip the display but I got nothing...

**Comment by shortbow123** [comment]
I am also using version 2.0.0.dev9 and I get None when I get_renderer_info()

**Comment by shortbow123** [comment]
To add more to my previous comments, my window still gets frozen but it says I am using metal

**Comment by xandark** [comment]
I think I'm having the identical issue but on Linux (KDE neon). 

I noticed that this occurred with pygame 2.0.0.dev8 and has continued with dev10. 

It happens with my personal game, and also when I run `python3 -m pygame.examples.aliens`. When I bring an arbitrary window in front of the Aliens game window and then bring Aliens to the front again, Aliens doesn't repaint its background; you see the objects drawing on the garbage of the previous window's contents. 

I've made a screen capture so you can see it here. (I tweaked the game to slow down the aliens so that the player wouldn't die and the window wouldn't disappear too quickly...)

[PyGame dev10 bad screen updates.zip](https://github.com/pygame/pygame/files/4713323/PyGame.dev10.bad.screen.updates.zip)

I've also tried `python3 -m pygame.examples.setmodescale` and the background would repaint itself properly, all good there. This was its console output:

```
pygame 2.0.0.dev10 (SDL 2.0.12, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
desktops [(1366, 768)]
renderer: opengl flags: 0b1010
accelerated
render to texture
```
 
Anything else you need to know?

**Comment by robertpfeiffer** [comment]
Not to be super condescending, but if you lose in aliens, the game stops updating and quits, right? Are you sure it isn't that? Maybe we should add an animated (GAME OVER, PRESS ANY KEY TO QUIT) screen to this game to make this easier to test, or make the game pause when it loses focus.

If it *isn't* that, we'd need to look into the way `pygame.display.update` actually works on mac and X11, including the different code paths SDL2 takes on these platforms.

**Comment by MyreMylar** [comment]
It's not that - you can how it looks in the attached video.

I do suspect it is an artefact of dirty rect optimisation for the aliens game, because pygame clearly is still updating, it's just only updating the display surface under the aliens that move.

Perhaps display.update() calls using the rects argument need to check for changes in the the SDL_WINDOW_MOUSE_FOCUS flag and then repaint the whole screen once rahter than using the rects?

**Comment by rethanon** [comment]
For what it's worth I can't replicate the issue, works fine on my MacBook running Catalina 10.15.5 using pygame 2.0.0.dev10 and python 3.8.3, although

**Comment by shortbow123** [comment]
I haven’t tried the dev10 version yet but I also installed Kivy and removed
it if that helps at all
