### ISSUE TITLE
No module named 'pygame.pypm' when initializing midi (2.0.0-dev10)

### ISSUE THREAD

**Issue by sakuya9t** [pygame/pygame#1931]
Hello, I recent got this error on my Mac when I try to use the midi module.

**Steps to reproduce:**
1. pip3 install pip3 install pygame==2.0.0-dev10
2. open python console
3. do following code block:
```
import pygame
import pygame.midi
pygame.init()
pygame.midi.init()
```
4. get following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pygame/midi.py", line 79, in init
    import pygame.pypm
ModuleNotFoundError: No module named 'pygame.pypm'
```

**Comment by sakuya9t** [comment]
1. This issue doesn't exist on windows 2.0.0-dev10
2. This issue doesn't exist on mac 1.9.6

**Comment by illume** [comment]
Thanks for the report.

This is related to the new build system(conan) being used on mac. There was no portmidi package I could find at the time, and forgot about it before the release. This is the conan issue: https://github.com/pygame/pygame/issues/997

**Comment by michamusic** [comment]
is there a solution?

**Comment by illume** [comment]
The solution is for someone to package portmidi as a 'conan' package. Unfortunately there isn't one still.

Another option is to compile pygame from source with homebrew on mac.
```
brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf portmidi
git clone https://github.com/pygame/pygame.git
cd pygame
python setup.py -config -auto -sdl2
python setup.py install
```

**Comment by illume** [comment]
This is fixed in #2187 and will be part of the next dev release.

**Comment by illume** [comment]
Hopefully `pygame==2.0.0.dev20` fixes this properly.

**Comment by NotVeryGoodAtCodingButOk** [comment]
I am still getting this issue on mac with pygame version 2.0.2.dev1

Is there anything else that I can try to get this fixed?

**Comment by Gabriel-522277** [comment]
The same problem for me, but my computer is a Win 10 -PC. The error message is:
**import pygame.pypm as pypm
ImportError: DLL load failed while importing pypm: Le module spécifié est introuvable.**

**MIDI.py** exists in my site-packages\pygame directory, but no **PYPM.py** at that location.
Is there a solution for me ? Is it possible to download this file ?
Thanks a lot for your help !

**Comment by Gabriel-522277** [comment]
Since my previous comment, I found     **pypm.cp38-win32.pyd** 
in this directory:   **Lib > site-packages > pygame**
Can that file repair my problem ? Thanks for your help.

**Comment by illume** [comment]
@Gabriel-522277 What version of pygame/python are you using? I assume you've tried uninstalling pygame, and installing the latest pygame?

**Comment by Gabriel-522277** [comment]
Hi René,
Thank you for your answer !
Your surname let me think that you could speak French. If it is the case, the next time, it will be easier for me to speak french 😊 !
Anyway, I dont use Pygame a long time age (perhaps 1 month ?).
Now, I’m using pygame 2.0.1 (SDL 2.0.12, Python 3.8.1).
I had no idea of what to do. According to you, which Pygame version should I install with Python 3.8.1 ?

And what to do to uninstall Pygame 2.0.1 ?

It’s very nice of you to help me, especially on a Sunday !
Thanks a lot.

Gabriel

De : René Dudfield
Envoyé le :dimanche 6 février 2022 14:52
À : pygame/pygame
Cc : Gabriel-522277; Mention
Objet :Re: [pygame/pygame] No module named 'pygame.pypm' when initializingmidi (2.0.0-dev10) (#1931)

@Gabriel-522277 What version of pygame/python are you using? I assume you've tried uninstalling pygame, and installing the latest pygame?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gabriel-522277** [comment]
Your advice was successful ! I uninstalled pygame, and then installed.
With Pygame version 2.1.2, pygame.midi is now accepted.
Thanks a lot !

**Comment by ei14** [comment]
Issue still occurs in pygame 2.1.3 (SDL 2.26.5, Python 3.11.3).

**Comment by hooby3dfx** [comment]
This issue is occurring on pygame 2.6.1 (SDL 2.32.10, Python 3.14.5)
26.5.1 (25F80) running on M3 Mac
pygame-2.6.1-cp314-cp314-macosx_14_0_arm64.whl

It seems that this build is not including pygame.pypm?

**Comment by hooby3dfx** [comment]
Scratch that - I needed to reinstall pygame after installing sdl2 and other dependencies!
