### ISSUE TITLE
X11 display driver does not respect pygame.SCALED attribute

### ISSUE THREAD

**Issue by DollarStarNova** [pygame/pygame#1958]
On windows, with the same python and pygame versions, this works fine, so I think its a problem with the x11 driver.

To Reproduce:

Python: 3.8.0
Pip install pygame==2.0.0dev10 (all versions are broken though)
Ubuntu

Expected Behaviour: 
Resizing window resizes all items in window

Actual Behaviour:
Resizing window does not change size of items in window.

```
import pygame

resolution = [1280, 720]
flags = pygame.RESIZABLE | pygame.SCALED
pygame.init()
mainwindow = pygame.display.set_mode(resolution, flags=flags)

pygame.draw.rect(mainwindow, (255, 0, 0), (200, 200, 100, 100))
pygame.draw.rect(mainwindow, (255, 0, 0), (400, 200, 100, 100))
pygame.draw.rect(mainwindow, (255, 0, 0), (200, 400, 100, 100))
pygame.draw.rect(mainwindow, (255, 0, 0), (400, 400, 100, 100))
pygame.draw.rect(mainwindow, (255, 0, 0), (1270, 0, 10, 10))
pygame.draw.rect(mainwindow, (255, 0, 0), (1270, 710, 10, 10))
pygame.draw.rect(mainwindow, (255, 0, 0), (0, 710, 10, 10))
pygame.draw.rect(mainwindow, (255, 0, 0), (0, 0, 10, 10))

while True:
    pygame.display.flip()
    for event in pygame.event.get():
        if event.type == pygame.QUIT or event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            pygame.quit()
            quit(0)
```

-Spec of Computer bug encountered on (not tested on other linux installs yet)-
Processor		: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
Memory		: 7138MB (3978MB used)
Machine Type		: Laptop
Operating System		: Ubuntu 19.10
Date/Time		: Wed 17 Jun 2020 19:42:01 BST
-Display-
Resolution		: 1920x1080 pixels
OpenGL Renderer		: AMD RAVEN (DRM 3.33.0, 5.3.0-46-generic, LLVM 9.0.0)
X11 Vendor		: The X.Org Foundation

**Comment by robertpfeiffer** [comment]
Thank you for the detailed bug report. This has been fixed in master already and will be available to everybody in the next dev snapshot release. Feel free to re-open the issue if it persists, or if you can reproduce the bug based on the current master.

**Comment by DollarStarNova** [comment]
@robertpfeiffer I built the latest master and this fixed scaling by pressing the maximise window button but it does not fix dragging to resize the window.
