### ISSUE TITLE
Possible game-crashing bug with set_timer? Doesn't crash on older version of pygame

### ISSUE THREAD

**Issue by robertgoodwin00** [pygame/pygame#3128]
windows
python 3.10.4
SDL 2.0.18
pygame 2.1.2

The program quietly crashes at certain points without anything to say (no error message, try/except raises no exceptions). Problems seems to be related to events and possibly set_timer. I found that if I comment out this certain line of code then the problem goes away:

pygame.time.set_timer(ANIMATE_BANNER,0)

However, if I comment that out then the animation goes on forever.

Using pygame 1.9.4 it never crashes. 

I'm afraid I don't have any helpful code to show. I tried to make a simpler version of the code for that purpose but just can't seem to reproduce it outside of my main program. (it doesn't happen consistently even then) Perhaps someone else with a similar problem can shed more light?

**Comment by ankith26** [comment]
Hi, thanks for the bug report!

Yup, this issue seems related to timers.
A minimal reproducer would be greatly appreciated in debugging something like this, but if that's not possible, could you identify the points where your app crashes? I'd like to know which pygame function specifically crashes.
If your app is not too large and you don't mind sharing it, I'd love to take a look at it and try to debug.

I am working on this function ATM in PR #3062 so you could try using that branch to see if your problem can be fixed (fair warning, that branch is still very WIP and may have other bugs and stuff so I don't recommend doing this for the moment, but maybe we can try this later)

**Comment by robertgoodwin00** [comment]
Hi, my app is large. I made a separate version of it with most of the graphics stripped out that I can share with you but it still comes out to 160 MB and zip compression doesn't help much. It also has Planes 0.6.0 as a dependency, which is a gui framework by Florian Berger which is on the pygames projects page, which itself needed a few modifications in order to work on Python 3. If you still would like to see it I can explain what to do and how to reproduce the problem. How would you like me to get it to you?

**Comment by ankith26** [comment]
you could either make it open-source on your github if you like, so that others can see it too, or if that's not an option, you can mail me at itsankith26@gmail.com

**Comment by robertgoodwin00** [comment]
Okay, I've made a private repository for it (the simpler version) and invited you to it. I put a README in there with instructions on how to reproduce the bug.

**Comment by ankith26** [comment]
Hi! I have joined the repo as a collaborator but the repo seems to be empty ATM, did you forget to push your changes to github on that repo?

**Comment by robertgoodwin00** [comment]
Oh goodness you're right. I'm scratching my head because I pushed it earlier and trying to push it now tells me that everything is up-to-date. But there's no code in there lol. Let me see what I'm missing...

**Comment by ankith26** [comment]
Cloned your codebase, installed dependencies with the hacks, but I still could not get it to work because some files were still missing from your project on github... Anyways, I see codebase is large and finding the root cause here would be tedious and time-consuming. 
I'd appreciate it if you to try to install pygame from #3062, you can get wheels (binaries) for your platform from github actions artifacts, and test whether the issue still reproduces.
Meanwhile I will try to test and come up with more minimal testcases to hopefully reproduce this issue, maybe picking some bits from the code you have provided

**Comment by robertgoodwin00** [comment]
I'd need to be walked through it more. So I used the CLI to get it on my system, then from the pygame directory tried "py -3 setup.py", answered 'y' when prompted whether to do default install, had it fail with the following:

 File "C:\Users\rober\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

I haven't done anything with wheels though.

**Comment by ankith26** [comment]
Since compiling pygame yourself can be a bit of a hassle, [here is a link](https://ci.appveyor.com/project/pygame/pygame/builds/43198388) to the appveyor run on the latest commit of my linked PR. Choose the build matching your python version and architecture (x86 or x64), go to the artifacts tab and download a "wheel file". Uninstall any older pygame versions, and run `pip install [wheelname]` in the directory where you locally downloaded it.

**Comment by robertgoodwin00** [comment]
Done.
My app is now silently quitting before the title screen at this particular line:
text_surface = font.render("WHERE", True, col)

(font is previously defined as a pygame.font.Font object)

**Comment by ankith26** [comment]
This new issue you mention, does it go away if you comment the `pygame.time.set_timer(ANIMATE_BANNER,0)` line? I'm trying to identify whether this is a new issue (either in pygame or in your code), and whether the timers PR fixed the old issue for you

**Comment by ankith26** [comment]
Hmmm... can you run your app in "python dev mode" with 
`python3 -X dev -X tracemalloc=5 woc.py`

This is elaborated more in the [python docs](https://docs.python.org/3/library/devmode.html) of the same, but TL;DR it should be helpful for debugging, since it prints a traceback on crash and may give some more useful info to work with.

Another, more tricky option is using gdb which should surely print a useful backtrace here, but since that is a bit more complicated than the way I mentioned above, can you please try that first and report back?

**Comment by robertgoodwin00** [comment]
Regarding the fontsize issue:
Windows fatal exception: code 0xc0000028
etc
(the trace just tells the line I already identified)

Regarding the timer issue:
Windows fatal exception: access violation

Current thread 0x00002ef4 (most recent call first):
  <no Python frame>

Thread 0x00001f78 (most recent call first):
  File "C:\Users\rober\AppData\Local\Programs\Python\Python310\lib\site-packages\planes\__init__.py", line 404 in render
  File "C:\Users\rober\AppData\Local\Programs\Python\Python310\lib\site-packages\planes\__init__.py", line 928 in render
etc

I tracked down what that line in planes is and it's this:
self.rendersurface = self.image.copy()

**Comment by robertgoodwin00** [comment]
Ok I replaced constant types with pygame.event.custom_type() per your recommendation in #2. I also got rid of almost all del statement per #1. Unfortunately that did not solve the problem and it still crashes.

As for #3, at this late stage in the project I can't really replace the dated python 2 library without an immense amount of work. (I began this project 10 years ago when it seemed to be the best library available)

**Comment by ankith26** [comment]
Hrmmm... okay I am running out of ideas... I think I could debug this with a proper debugger like gdb, compiling a debug build pygame myself and testing with your app if I got the missing files from your codebase, can you update your github repo with the current state of the codebase as a zip file (yes to make it easier for you to upload, and me to pull) 

BTW, thanks for the support so far for debugging this ;)

**Comment by robertgoodwin00** [comment]
Strangely, I can't reproduce the crashing with the current codebase any more! Whether it was something we did, or some other random thing I've done since, it appears to be fixed now?? I don't think it was the pygame.event.custom_type() thing tho, because I'm testing it again both ways and it's not making a difference.

Well I'll hook you up with the old version of the codebase which still crashes then. I made a new repository for that and invited you. (problem with the last one was something stupid I did with the git file)

No problem :)

**Comment by ankith26** [comment]
Okay... I could finally reproduce your issue in pygame 2.1.2 testing on windows 11 and also Ubuntu 21.10 running under WSL. But I could not reproduce it in my branch, so it should have been fixed inadvertently when I did changes on there.

Anyways, here is the gdb backtrace of this issue on Ubuntu with pygame 2.1.2 for anyone curious
```
Thread 2 "SDLTimer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3936640 (LWP 502)]
0x00007ffff67050c8 in pgEvent_FillUserEvent (e=0x2, event=0x7ffff3935d80) at src_c/event.c:603
603         Py_INCREF(e->dict);
```
another run:
```
Thread 2 "SDLTimer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3936640 (LWP 609)]
0x00007ffff67050c8 in pgEvent_FillUserEvent (e=0xffffffffffffffff, event=0x7ffff3935d80) at src_c/event.c:603
603         Py_INCREF(e->dict);
(gdb) bt
#0  0x00007ffff67050c8 in pgEvent_FillUserEvent (e=0xffffffffffffffff, event=0x7ffff3935d80) at src_c/event.c:603
#1  0x00007ffff62b0a6a in timer_callback (interval=10, param=0x5) at src_c/time.c:178
#2  0x00007ffff74e2c42 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#3  0x00007ffff74e2683 in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x00007ffff7569f8d in  () at /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#5  0x00007ffff7cf1947 in start_thread (arg=<optimized out>) at pthread_create.c:435
#6  0x00007ffff7d81a44 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```
Somehow the first argument to `pgEvent_FillUserEvent` call in the `timer_callback` callback seems to get wrong values, when they are expected to be pointers.

So yeah, this issue should be fixed when my PR is merged.

Another font issue you mentioned, I dug deeper into that, and my findings so far
1) It happens only on windows 11 not Ubuntu 21.10
2) It happens on `main` but not 2.1.2
3) It happens with one specific font of your game
4) It does not happen on all font sizes, but only on some

It is unrelated to timers, this issue, and my PR to fix this issue, so I'd like to open a new issue to track this, and I need your permission to reveal the font publicly (hopefully it does not mess with any licensing)

**Comment by robertgoodwin00** [comment]
Ah, very good.
Sure, you can reveal the font. It's a completely free font I downloaded from somewhere a couple weeks ago.

**Comment by chnlkw** [comment]
I have similar issue when using pygame.event.get() with pygame.set_timer()
The program will definetly crash when repeating running multiple times.

Crash environment:
* windows 11 (64 bit)
* python 3.9.12 (64 bit) and 3.7.9 (64 bit) (both tested)
* pygame 2.1.2

but it doesn't crash on pygame 2.0.0

here is the simplest code:

```python
import pygame

class UserQuitException(Exception):
    pass

display_width, display_height = 1920, 1080

flag_fullscreen = 0

background = (0, 0, 0)

timeout_event = pygame.USEREVENT + 1

def wait4key(keys: dict, timeout_ms = None):
    print('clear event')
    pygame.event.get() # 清空事件
    print('wait4key keys: {} timeout : {}'.format(keys, timeout_ms))
    if timeout_ms != None:
        pygame.time.set_timer(timeout_event, timeout_ms)
    t_start = pygame.time.get_ticks()  # ms level time count
    ret = None
    found = False
    while not found:
        for event in pygame.event.get():
            if event.type == pygame.QUIT or event.type == pygame.KEYDOWN and event.key == pygame.K_q:
                pygame.quit()
                raise UserQuitException
            if event.type == pygame.KEYDOWN:
                if event.key in keys:
                    ret = keys[event.key]
                    found = True
            if event.type == timeout_event:
                found = True

    t_end = pygame.time.get_ticks()  # ms level time count
    time = t_end - t_start
    pygame.time.set_timer(timeout_event, 0) # disable timer anyway
    print("key : {}, time : {}".format(ret, time))
    return ret, time 

def game():
    pygame.init()
    screen = pygame.display.set_mode([display_width, display_height], pygame.HWSURFACE | pygame.DOUBLEBUF | flag_fullscreen)
    pygame.display.set_caption('test')

    pygame.display.flip()
    screen.fill(background)
    _ = wait4key({}, 1) # if comment this line, program will not crash

    ret = []
    print('quit')
    pygame.quit()
    print('ret')
    return ret

n=10000
for i in range(n):
    game()
```

**Comment by ankith26** [comment]
Oh, thanks a lot for the reproducer! I can confirm this segfaults for me to locally with 2.1.2 and the PR I linked should fix this issue.
(pretty sure I introduced this bug in the first place in 2.0.1 so... sorry :/)
It should be the same issue, in both programs, the `pygame.time.set_timer(timeout_event, 0)` line triggers the segfault, and the smaller the time delta the more probable the segfault, by the looks of things...

**Comment by robertgoodwin00** [comment]
Is there a version of pygame (that I don't have to compile myself) I can use that doesn't have this issue? Since the crashing makes my game virtually unplayable on 2.1.3dev5.

**Comment by ankith26** [comment]
I think 2.0.0 is not impacted by this bug, you can try it. Although it's a bit old at this point and may have other bugs that got patched in versions after it

**Comment by robertgoodwin00** [comment]
Hmm I can't seem to install 2.0.0 with pip. Getting  [SSL: CERTIFICATE_VERIFY_FAILED]. Looks like my only option is to go back to 1.9.4 which I still have installed with python 2 though they're much slower :-(

**Comment by robertgoodwin00** [comment]
I guess I can work around it by not using set_timer to stop animations. That means they go on forever (off-screen) but at least nothing should crash.

**Comment by nthykier** [comment]
I noted the reference to this bug in https://github.com/rchen152/maze/commit/a79ac8b70f0f15b05f21918406fa2c9af8a6cb73 with the note:

> * Work around segfault caused by pygame/pygame#3128
>  by not calling set_timer(..., 0).

Looks like someone found a very concrete trigger for this problem.

**Comment by nthykier** [comment]
Oh, this is already stated previously in the thread. My bad. :-/

**Comment by illume** [comment]
This should be fixed in pygame==2.5.0
